pipeline {
     agent any
     stages {
        stage("Checkout") {
            steps {
                git url: 'https://github.com/nagabhushanamn/calculator.git'
            }
          }
        stage("Compile") {
		    steps {
                script{
                    def project = 'web-calculator'
                    sh "./${project}/gradlew clean compileJava"
                }
		    }
		}
		stage("Unit test") {
			script{
                    def project = 'web-calculator'
                    sh "./${project}/gradlew test"
                }
		}
     }
}