pipeline {
     agent any
     stages {
        stage("Checkout") {
            steps {
                git url: 'https://github.com/nagabhushanamn/calculator.git'
            }
          }
        stage("Compile") {
        		def project = 'web-calculator'
		    steps {
                //echo "./${project}"
		        sh "./${project}/gradlew clean compileJava"
		    }
		}
		stage("Unit test") {
			def project = 'web-calculator'
		    steps {
		        sh "./${project}./gradlew test"
		    }
		}
     }
}